spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testdb?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2b8
    username: root
    password: 123456
